### ISSUE TITLE
Angular 9 problem - main.single-spa.ts is missing from the Typescript compilation

### ISSUE THREAD

**Issue by joeldenning** [single-spa/single-spa-angular#128]
```
ERROR in ./src/main.single-spa.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /Users/joeldenning/code/angular-test/src/main.single-spa.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/Users/joeldenning/code/angular-test/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:909:23)
    at /Users/joeldenning/code/angular-test/node_modules/@ngtools/webpack/src/loader.js:41:31
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by joeldenning** [comment]
Looks like we need a schematic for modifying the tsconfig to fix this. I confirmed locally that adding `"main.single-spa.ts"` to the tsconfig.app.json file fixes the error

**Comment by qaxqaxqax** [comment]
From my experience unmount also does not work with 9.0.0

**Comment by joeldenning** [comment]
@qaxqaxqax can you create a new issue for that? I'd like to trap each issue with Angular 9 separately
