### ISSUE TITLE
Unable to build Angular 7 projects using the documentation

### ISSUE THREAD

**Issue by subodhkumarWM** [single-spa/single-spa-angular#185]
Trying to build artefacts for Angular7 projects,
Steps to replicate:
* ng new <project_name>
* ng add single-spa-angular
* ng build --prod

getting the below error,
```
Builder 'single-spa-angular:build' cannot be resolved.
Error: Builder 'single-spa-angular:build' cannot be resolved.
    at MergeMapSubscriber._loadJsonFile.pipe.operators_1.concatMap [as project] (/Users/subodhk/Downloads/bWmSspa_1.0/wm-ng-app/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect.js:139:46)
    at MergeMapSubscriber._tryNext (/Users/subodhk/Downloads/bWmSspa_1.0/wm-ng-app/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/Users/subodhk/Downloads/bWmSspa_1.0/wm-ng-app/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/subodhk/Downloads/bWmSspa_1.0/wm-ng-app/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/Users/subodhk/Downloads/bWmSspa_1.0/wm-ng-app/node_modules/@angular/cli/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/Users/subodhk/Downloads/bWmSspa_1.0/wm-ng-app/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/Users/subodhk/Downloads/bWmSspa_1.0/wm-ng-app/node_modules/@angular/cli/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/Users/subodhk/Downloads/bWmSspa_1.0/wm-ng-app/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/Users/subodhk/Downloads/bWmSspa_1.0/wm-ng-app/node_modules/@angular/cli/node_modules/@angular-devkit/core/node/host.js:172:21)
    at Observable._trySubscribe (/Users/subodhk/Downloads/bWmSspa_1.0/wm-ng-app/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:44:25)
```

**Comment by subodhkumarWM** [comment]
Thanks a lot for the confirmation @joeldenning
