### ISSUE TITLE
Error while running 'ng add single-spa-angular@3' with version 3.5

### ISSUE THREAD

**Issue by subodhkumarWM** [single-spa/single-spa-angular#199]
Steps:
Angular cli v7

```
ng new sspa-eg
ng add single-spa-angular@3
```

Gets below error
```
Path "/Users/subodhk/XPs/NgXp/S3xp/sspa/node_modules/single-spa-angular/src/schematics/ng-add/schema.json" does not exist.
Error: Path "/Users/subodhk/XPs/NgXp/S3xp/sspa/node_modules/single-spa-angular/src/schematics/ng-add/schema.json" does not exist.
    at readFile (/Users/subodhk/XPs/NgXp/S3xp/sspa/node_modules/@angular-devkit/schematics/tools/file-system-utility.js:17:15)
    at Object.readJsonFile (/Users/subodhk/XPs/NgXp/S3xp/sspa/node_modules/@angular-devkit/schematics/tools/file-system-utility.js:45:29)
    at NodeModulesEngineHost.createSchematicDescription (/Users/subodhk/XPs/NgXp/S3xp/sspa/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:182:48)
    at SchematicEngine.createSchematic (/Users/subodhk/XPs/NgXp/S3xp/sspa/node_modules/@angular-devkit/schematics/src/engine/engine.js:219:38)
    at CollectionImpl.createSchematic (/Users/subodhk/XPs/NgXp/S3xp/sspa/node_modules/@angular-devkit/schematics/src/engine/engine.js:69:29)
    at AddCommand.getSchematic (/Users/subodhk/XPs/NgXp/S3xp/sspa/node_modules/@angular/cli/models/schematic-command.js:130:27)
    at AddCommand.runSchematic (/Users/subodhk/XPs/NgXp/S3xp/sspa/node_modules/@angular/cli/models/schematic-command.js:262:32)
    at AddCommand.executeSchematic (/Users/subodhk/XPs/NgXp/S3xp/sspa/node_modules/@angular/cli/commands/add-impl.js:134:31)
    at AddCommand.run (/Users/subodhk/XPs/NgXp/S3xp/sspa/node_modules/@angular/cli/commands/add-impl.js:105:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by joeldenning** [comment]
> Can this issue be moved to single-spa/single-spa-angular from single-spa?

Done

**Comment by joeldenning** [comment]
The fix for this is released in https://github.com/single-spa/single-spa-angular/releases/tag/v3.5.1.

```
ng add single-spa-angular@angular-pre-9`

# or
ng add single-spa-angular@3.5.1
```
