### ISSUE TITLE
'Error: Collection "single-spa-angular" cannot be resolved' while running `ng add single-spa-angular@3.5.1`

### ISSUE THREAD

**Issue by Den-dp** [single-spa/single-spa-angular#226]
`ng add single-spa-angular@3.5.1` (and `3.5.2`) fails to run on `angular@7` project.

### Demonstration
```
> npm i -g @angular/cli@7.3.10
```
```
> ng new ngcli7310
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
```
```
> cd .\ngcli7310\
```
```
> ng add single-spa-angular@3.5.1
```

### Expected Behavior

Schematics should be installed without errors.

### Actual Behavior

```
> ng add single-spa-angular@3.5.1
Installing packages for tooling via npm.
...
+ single-spa-angular@3.5.1
added 2 packages from 1 contributor and audited 1158 packages in 9.935s

Installed packages for tooling via npm.
Collection "single-spa-angular" cannot be resolved.
Error: Collection "single-spa-angular" cannot be resolved.
    at NodeModulesEngineHost._resolveCollectionPath (C:\dev\temp\ngcli7310\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:91:15)
    at NodeModulesEngineHost.createCollectionDescription (C:\dev\temp\ngcli7310\node_modules\@angular-devkit\schematics\tools\file-system-engine-host-base.js:111:27)
    at SchematicEngine._createCollectionDescription (C:\dev\temp\ngcli7310\node_modules\@angular-devkit\schematics\src\engine\engine.js:147:40)
    at SchematicEngine.createCollection (C:\dev\temp\ngcli7310\node_modules\@angular-devkit\schematics\src\engine\engine.js:140:43)
    at AddCommand.getCollection (C:\dev\temp\ngcli7310\node_modules\@angular\cli\models\schematic-command.js:123:35)
    at AddCommand.runSchematic (C:\dev\temp\ngcli7310\node_modules\@angular\cli\models\schematic-command.js:262:50)
    at AddCommand.executeSchematic (C:\dev\temp\ngcli7310\node_modules\@angular\cli\commands\add-impl.js:134:31)
    at AddCommand.run (C:\dev\temp\ngcli7310\node_modules\@angular\cli\commands\add-impl.js:105:21)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async AddCommand.validateAndRun (C:\dev\temp\ngcli7310\node_modules\@angular\cli\models\command.js:124:20)
    at async Object.runCommand (C:\dev\temp\ngcli7310\node_modules\@angular\cli\models\command-runner.js:147:16)
    at async default_1 (C:\dev\temp\ngcli7310\node_modules\@angular\cli\lib\cli\index.js:27:31)
```
---

Probably related with #199

**Comment by jimmyhdolores** [comment]
For angular 7 you have to do the manual installation https://single-spa.js.org/docs/ecosystem-angular#manual-installation;  in my case I used version 3.3.2 of single-spa-angular, if you have problems with routing you have to register the application
https://github.com/single-spa/single-spa-angular/issues/218#issuecomment-647065612

**Comment by joeldenning** [comment]
Angular 7 uses a [custom single-spa Angular builder](https://github.com/single-spa/single-spa-angular/blob/3.x/src/builders/single-spa-webpack-builder.ts) to modify the webpack config instead of using the official Angular custom webpack builder. The reason is that the custom webpack builder did not exist until Angular 8.

The schematics should work in Angular 7. Any help fixing this would be appreciated.

**Comment by Den-dp** [comment]
@joeldenning looks like it's broken since 3.5.0 and mainly because we stop publishing `builders.json` and `schematics.json` https://github.com/single-spa/single-spa-angular/commit/3dfe1eb1268011fb92a70f3fb035cc31c29864f6#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R32

Will provide a PR shortly

**Comment by joeldenning** [comment]
Released in https://github.com/single-spa/single-spa-angular/releases/tag/v3.5.3

**Comment by Den-dp** [comment]
Great! Thanks for responding to this so quickly. I really appreciate it.
