### ISSUE TITLE
create-single-spa does not work with Angular 11

### ISSUE THREAD

**Issue by daniloesk** [single-spa/single-spa-angular#304]
**Describe the bug or question**
"Cannot find module '@schematics/angular/utility/json-utils'" when creating Angular parcel with npx create-single-spa. The success message at the end is misleading. =)
It looks like json-utils was removed in Angular 11.

**To Reproduce**
Run `npx create-single-spa --dir . --moduleType app-parcel --framework angular`.

**Expected behavior**
The Angular parcel is generated without errors.

**Screenshots and/or console output**
```
USER:single-spa$ npx create-single-spa --dir . --moduleType app-parcel --framework angular
? Project name (can use letters, numbers, dash or underscore) mod1
? Do you want to enforce stricter type checking and stricter bundle budgets in the workspace?
  This setting helps improve maintainability and catch bugs ahead of time.
  For more information, see https://angular.io/strict No
? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? CSS
CREATE mod1/README.md (1013 bytes)
CREATE mod1/.editorconfig (274 bytes)
CREATE mod1/.gitignore (631 bytes)
CREATE mod1/angular.json (3519 bytes)
CREATE mod1/package.json (1194 bytes)
CREATE mod1/tsconfig.json (458 bytes)
CREATE mod1/tslint.json (3185 bytes)
CREATE mod1/.browserslistrc (703 bytes)
CREATE mod1/karma.conf.js (1099 bytes)
CREATE mod1/tsconfig.app.json (287 bytes)
CREATE mod1/tsconfig.spec.json (333 bytes)
CREATE mod1/src/favicon.ico (948 bytes)
CREATE mod1/src/index.html (290 bytes)
CREATE mod1/src/main.ts (372 bytes)
CREATE mod1/src/polyfills.ts (2826 bytes)
CREATE mod1/src/styles.css (80 bytes)
CREATE mod1/src/test.ts (753 bytes)
CREATE mod1/src/assets/.gitkeep (0 bytes)
CREATE mod1/src/environments/environment.prod.ts (51 bytes)
CREATE mod1/src/environments/environment.ts (662 bytes)
CREATE mod1/src/app/app.module.ts (314 bytes)
CREATE mod1/src/app/app.component.css (0 bytes)
CREATE mod1/src/app/app.component.html (25725 bytes)
CREATE mod1/src/app/app.component.spec.ts (934 bytes)
CREATE mod1/src/app/app.component.ts (208 bytes)
CREATE mod1/e2e/protractor.conf.js (904 bytes)
CREATE mod1/e2e/tsconfig.json (274 bytes)
CREATE mod1/e2e/src/app.e2e-spec.ts (655 bytes)
CREATE mod1/e2e/src/app.po.ts (274 bytes)
✔ Packages installed successfully.
    Directory is already under version control. Skipping initialization of git.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
An unhandled exception occurred: Cannot find module '@schematics/angular/utility/json-utils'
Require stack:
- /home/USER/single-spa/mod1/node_modules/single-spa-angular/schematics/ng-add/index.js
- /home/USER/single-spa/mod1/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/USER/single-spa/mod1/node_modules/@angular-devkit/schematics/tools/index.js
- /home/USER/single-spa/mod1/node_modules/@angular/cli/utilities/json-schema.js
- /home/USER/single-spa/mod1/node_modules/@angular/cli/models/command-runner.js
- /home/USER/single-spa/mod1/node_modules/@angular/cli/lib/cli/index.js
- /opt/nvm/versions/node/v14.15.1/lib/node_modules/@angular/cli/lib/init.js
- /opt/nvm/versions/node/v14.15.1/lib/node_modules/@angular/cli/bin/ng
See "/tmp/ng-fPtBOi/angular-errors.log" for further details.
For further routing setup, see https://single-spa.js.org/docs/ecosystem-angular#configure-routes
Project setup complete!
Steps to test your Angular single-spa application:
1. Run 'npm run serve:single-spa:mod1'
2. Go to http://single-spa-playground.org/playground/instant-test?name=mod1&url=%2F%2Flocalhost%3A4200%2Fmain.js&framework=angular to see it working!
```

**Error log**
```
[error] Error: Cannot find module '@schematics/angular/utility/json-utils'
Require stack:
- /home/USER/single-spa/mod1/node_modules/single-spa-angular/schematics/ng-add/index.js
- /home/USER/single-spa/mod1/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/USER/single-spa/mod1/node_modules/@angular-devkit/schematics/tools/index.js
- /home/USER/single-spa/mod1/node_modules/@angular/cli/utilities/json-schema.js
- /home/USER/single-spa/mod1/node_modules/@angular/cli/models/command-runner.js
- /home/USER/single-spa/mod1/node_modules/@angular/cli/lib/cli/index.js
- /home/USER/.npm/_npx/354442/lib/node_modules/@angular/cli/lib/init.js
- /home/USER/.npm/_npx/354442/lib/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/USER/single-spa/mod1/node_modules/single-spa-angular/schematics/ng-add/index.js:10:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at new ExportStringRef (/home/USER/single-spa/mod1/node_modules/@angular-devkit/schematics/tools/export-ref.js:19:25)
    at NodeModulesEngineHost._resolveReferenceString (/home/USER/single-spa/mod1/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:95:21)
    at NodeModulesEngineHost.createSchematicDescription (/home/USER/single-spa/mod1/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:174:34)
    at SchematicEngine.createSchematic (/home/USER/single-spa/mod1/node_modules/@angular-devkit/schematics/src/engine/engine.js:215:38)
    at CollectionImpl.createSchematic (/home/USER/single-spa/mod1/node_modules/@angular-devkit/schematics/src/engine/engine.js:70:29)
```

**Additional context**
* @angular/cli 11.0.2
* Node.js
  * 14.15.0
  * 14.15.1
* OS: linux x64

**Workaround**
To generate a parcel using Angular 10 instead:
```
mkdir angular10
cd angular10
npm install @angular/cli@10 create-single-spa
node_modules/.bin/create-single-spa --dir . --moduleType app-parcel --framework angular
```
Then move the generated directory outside of angular10 directory.

**Comment by filoxo** [comment]
Transferring this issue to single-spa-angular. This isn't an issue in create-single-spa but rather that the single-spa-angular generator isn't yet working with Angular 11. Angular 11 support was implemented in https://github.com/single-spa/single-spa-angular/pull/301 but that has yet to be released.

**Comment by joeldenning** [comment]
I just released https://github.com/single-spa/single-spa-angular/releases/tag/v4.8.0 - try again and see if it works now?

**Comment by daniloesk** [comment]
> Transferring this issue to single-spa-angular. This isn't an issue in create-single-spa but rather that the single-spa-angular schematic isn't yet working with Angular 11. Angular 11 support was implemented in #301 but that has yet to be released.

That makes a lot of sense, but since single-spa-angular was not used directly, create-single-spa should handle it somehow. Maybe it is a good idea to limit the Angular version so it does not break with new releases.

I will test it as soon as I can.

**Comment by daniloesk** [comment]
> I just released https://github.com/single-spa/single-spa-angular/releases/tag/v4.8.0 - try again and see if it works now?

I just ran the same command and the command ended with no errors.

**Comment by filoxo** [comment]
> create-single-spa should handle it somehow. Maybe it is a good idea to limit the Angular version so it does not break with new releases.

I disagree. That logic for handling compatible versions should be contained inside of the single-spa-angular generator.

**Comment by joeldenning** [comment]
Agreed - the single-spa-angular project is where we change things to support new versions of Angular
