### ISSUE TITLE
Builder 'single-spa-angular:dev-server' cannot be resolved.

### ISSUE THREAD

**Issue by lidenggao** [single-spa/single-spa-angular#325]
### Question
I refer to the configuration here to complete the project
- https://single-spa.js.org/docs/ecosystem-angular/#angular-6
- https://single-spa.js.org/docs/ecosystem-angular/#manual-installation

```
"serve:single-spa:pms": "ng s --project pms --disable-host-check --port 4200 --deploy-url http://localhost:4200/ --live-reload false"
```
When I run the command 'npm run serve:single-spa:pms'，Get the error message：
```
> pms@0.0.0 serve:single-spa:pms E:\coding\hn-pms-frontend\apps\pms
> ng s --project pms --disable-host-check --port 4200 --deploy-url http://localhost:4200/ --live-reload false

Builder 'single-spa-angular:dev-server' cannot be resolved.
Error: Builder 'single-spa-angular:dev-server' cannot be resolved.
    at MergeMapSubscriber.project (E:\coding\hn-pms-frontend\apps\pms\node_modules\@angular-devkit\architect\src\architect.js:139:46)
    at MergeMapSubscriber._tryNext (E:\coding\hn-pms-frontend\apps\pms\node_modules\rxjs\internal\operators\mergeMap.js:65:27)
    at MergeMapSubscriber._next (E:\coding\hn-pms-frontend\apps\pms\node_modules\rxjs\internal\operators\mergeMap.js:55:18)
    at MergeMapSubscriber.Subscriber.next (E:\coding\hn-pms-frontend\apps\pms\node_modules\rxjs\internal\Subscriber.js:64:18)
    at MapSubscriber._next (E:\coding\hn-pms-frontend\apps\pms\node_modules\rxjs\internal\operators\map.js:52:26)
    at MapSubscriber.Subscriber.next (E:\coding\hn-pms-frontend\apps\pms\node_modules\rxjs\internal\Subscriber.js:64:18)
    at MapSubscriber._next (E:\coding\hn-pms-frontend\apps\pms\node_modules\rxjs\internal\operators\map.js:52:26)
    at MapSubscriber.Subscriber.next (E:\coding\hn-pms-frontend\apps\pms\node_modules\rxjs\internal\Subscriber.js:64:18)
    at Observable._subscribe (E:\coding\hn-pms-frontend\apps\pms\node_modules\@angular-devkit\core\node\host.js:172:21)
    at Observable._trySubscribe (E:\coding\hn-pms-frontend\apps\pms\node_modules\rxjs\internal\Observable.js:43:25)
```
### Environment

<pre><code>
Libs:
- Angular CLI: 6.2.7
- Node: 12.18.4
- OS: win32 x64
- Angular: 6.1.10
- single-spa-angular: "^4.0.0",

Others:
- @angular-devkit/architect         0.8.7
- @angular-devkit/build-angular     0.8.9
- @angular-devkit/build-optimizer   0.8.9
- @angular-devkit/build-webpack     0.8.9
- @angular-devkit/core              0.8.7
- @angular-devkit/schematics        0.8.7
- @angular/cli                      6.2.7
- @ngtools/webpack                  6.2.9
- @schematics/angular               0.8.7
- @schematics/update                0.8.7
- rxjs                              6.2.2
- typescript                        2.9.2
- webpack                           4.16.4
</code></pre>

**Comment by daniloesk** [comment]
The doc link in your post says "Angular 6 is supported by single-spa-angular@3" and it seems you are using ^4.0.0.

**Comment by arturovt** [comment]
@lidenggao as @daniloesk has mentioned you're using incompatible versions of Angular and single-spa-angular. Please, downgrade to the single-spa-angular@3. I'm closing it as "not an issue", feel free to re-open if I'm missing anything.
