### ISSUE TITLE
Angular: Unhandled Promise rejection: Cannot read property 'Symbol(Symbol.species)' of undefined ; Zone: <root>

### ISSUE THREAD

**Issue by mkurte** [single-spa/single-spa-angular#378]
Hey guys,

I'm pretty new with single-spa and still evaluating it.
I try to show some angular frontends with single-spa and it works fine except for one error I get in the developer console of chrome and firefox. I haven't tested any other browsers but I'm sure the error shows up everywhere:

```
Unhandled Promise rejection: Cannot read property 'Symbol(Symbol.species)' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'Symbol(Symbol.species)' of undefined
    at Module.e.then (zone.min.js:27)
    at k (zone.min.js:27)
    at zone.min.js:27
    at e.invokeTask (zone.min.js:13)
    at t.runTask (zone.min.js:13)
    at _ (zone.min.js:13)
    at t.invokeTask [as invoke] (zone.min.js:13)
    at p (zone.min.js:43)
    at HTMLScriptElement.h (zone.min.js:43) TypeError: Cannot read property 'Symbol(Symbol.species)' of undefined
    at Module.e.then (https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js:27:4318)
    at k (https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js:27:1549)
    at https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js:27:2804
    at e.invokeTask (https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js:13:7855)
    at t.runTask (https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js:13:2934)
    at _ (https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js:13:10171)
    at t.invokeTask [as invoke] (https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js:13:9016)
    at p (https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js:43:733)
    at HTMLScriptElement.h (https://cdn.jsdelivr.net/npm/zone.js@0.11.3/dist/zone.min.js:43:966)
```

So, somethings wrong with zone.js, and to be honest, I don't have a clue what this is. I also checked out the official angular examples from your docs page (https://github.com/angular-microfrontends) but I get the same error here.

I made a small monorepo where you can reproduce the error, you can find it here:
https://github.com/mkurte/single-spa-angular

I used Angular CLI Version 12 and create the single-spa-root config via `npx create-single-spa`.
Is there something I forgot or is this error new?

Many thanks in advance!

Cheers,
Matthias

PS: I'm not a native english speaker - so please excuse my bad english.

**Comment by rbj325** [comment]
It appears this is related to the upgrade to Angular 12 because prior Angular versions still work but with v12 I get this error.

**Comment by andreyjkee** [comment]
I have the same issue:
```
zone.js:1456 Uncaught TypeError: Cannot read property 'Symbol(Symbol.species)' of undefined
    at Module.ZoneAwarePromise.then (zone.js:1456)
    at resolvePromise (zone.js:1213)
    at zone.js:1321
    at ZoneDelegate.invokeTask (zone.js:434)
    at Zone.runTask (zone.js:205)
    at drainMicroTaskQueue (zone.js:620)
    at ZoneTask.invokeTask [as invoke] (zone.js:520)
    at invokeTask (zone.js:1656)
    at HTMLScriptElement.globalZoneAwareCallback (zone.js:1682)
ZoneAwarePromise.then @ zone.js:1456
resolvePromise @ zone.js:1213
(anonymous) @ zone.js:1321
ZoneDelegate.invokeTask @ zone.js:434
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:620
ZoneTask.invokeTask @ zone.js:520
invokeTask @ zone.js:1656
globalZoneAwareCallback @ zone.js:1682
setTimeout (async)
scheduleTask @ zone.js:3065
ZoneDelegate.scheduleTask @ zone.js:421
Zone.scheduleTask @ zone.js:248
Zone.scheduleMacroTask @ zone.js:271
scheduleMacroTaskWithCurrentZone @ zone.js:716
(anonymous) @ zone.js:3107
proto.<computed> @ zone.js:1015
h @ single-spa-layout.min.js:formatted:239
(anonymous) @ app-errors.js:9
handleAppError @ app-errors.js:9
(anonymous) @ load.js:147
ZoneDelegate.invoke @ zone.js:400
Zone.run @ zone.js:160
(anonymous) @ zone.js:1318
ZoneDelegate.invokeTask @ zone.js:434
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:620
ZoneTask.invokeTask @ zone.js:520
invokeTask @ zone.js:1656
globalZoneAwareCallback @ zone.js:1682
load (async)
customScheduleGlobal @ zone.js:1808
ZoneDelegate.scheduleTask @ zone.js:421
Zone.scheduleTask @ zone.js:248
Zone.scheduleEventTask @ zone.js:274
(anonymous) @ zone.js:1965
(anonymous) @ system.js:642
ZoneAwarePromise @ zone.js:1340
systemJSPrototype.instantiate @ system.js:637
systemJSPrototype.instantiate @ system.js:675
systemJSPrototype.instantiate @ system.js:711
systemJSPrototype.instantiate @ named-register.js:61
(anonymous) @ system.js:283
ZoneDelegate.invoke @ zone.js:400
Zone.run @ zone.js:160
(anonymous) @ zone.js:1318
ZoneDelegate.invokeTask @ zone.js:434
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:620
ZoneTask.invokeTask @ zone.js:520
invokeTask @ zone.js:1656
globalZoneAwareCallback @ zone.js:1682
load (async)
customScheduleGlobal @ zone.js:1808
ZoneDelegate.scheduleTask @ zone.js:421
Zone.scheduleTask @ zone.js:248
Zone.scheduleEventTask @ zone.js:274
(anonymous) @ zone.js:1965
(anonymous) @ system.js:642
ZoneAwarePromise @ zone.js:1340
systemJSPrototype.instantiate @ system.js:637
systemJSPrototype.instantiate @ system.js:675
systemJSPrototype.instantiate @ system.js:711
systemJSPrototype.instantiate @ named-register.js:61
(anonymous) @ system.js:283
ZoneDelegate.invoke @ zone.js:400
Zone.run @ zone.js:160
(anonymous) @ zone.js:1318
ZoneDelegate.invokeTask @ zone.js:434
Zone.runTask @ zone.js:205
drainMicroTaskQueue @ zone.js:620
Promise.then (async)
scheduleMicroTask @ zone.js:603
ZoneDelegate.scheduleTask @ zone.js:424
Zone.scheduleTask @ zone.js:248
Zone.scheduleMicroTask @ zone.js:268
scheduleResolveOrReject @ zone.js:1308
ZoneAwarePromise.then @ zone.js:1466
systemJSPrototype.import @ system.js:226
systemJSPrototype.import @ system.js:778
(anonymous) @ catalog:76
```

**Comment by arturovt** [comment]
I know it’s been so long since this issue was opened, but it’s an issue in the zone.js itself. I’ve made a PR with a fix, cannot guarantee the time when this will be merged and published.

**Comment by arturovt** [comment]
The fix has been merged into the Angular repository https://github.com/angular/angular/commit/e2eaac34b06a558145be41853f1d3585c1108880.
